.PHONY: all
all: clean test build lint

.PHONY: clean
clean:
	rm -rf ./dist c.out coverage.txt

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: copier-update
copier-update:
	copier update --trust --skip-answered

.PHONY: update
update:
	go list -f '{{ '{{' }}if not (or .Main .Indirect){{ '}}' }}{{ '{{' }}.Path{{ '}}' }}{{ '{{' }}end{{ '}}' }}' -m all | xargs --no-run-if-empty go get
	go mod tidy

.PHONY: build
build:{% if protobuf %} build-proto{% endif %}{% if binary %} build-go{% endif %}

.PHONY: release
release:{% if binary %} release-go{% endif %}

.PHONY: test
test: test-go

.PHONY: lint
lint:{% if protobuf %} lint-proto{% endif %} lint-go

.PHONY: coverage-report
coverage-report:
	cc-test-reporter before-build
	go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
	cp coverage.txt c.out
	cc-test-reporter after-build -t gocov -p $$(go list -m)

.PHONY: test-go
test-go:{% if protobuf %} build-proto{% endif %}
	go test -race -cover ./...

.PHONY: lint-go
lint-go:
	golangci-lint run

{%- if binary %}

.PHONY: build-go
build-go:
	goreleaser build --snapshot --clean

.PHONY: release-go
release-go:
	goreleaser release --clean
{%- endif %}

{%- if protobuf %}

.PHONY: lint-proto
lint-proto:
	buf lint

.PHONY: build-proto
build-proto:
	buf generate
{%- endif %}
