---
name: 'Build Docker Image'
description: 'Builds and optionally pushes a docker image to Dockerhub'

inputs:
  name:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tag/version'
    required: true
  push:
    description: 'Whether to push the image'
    default: false
  context:
    description: 'Path to docker context directory'
    default: '.'
    required: false
  dockerfile:
    description: 'Path to the Dockerfile, relative to context'
    default: 'Dockerfile'
    required: false
  dockerhub_username:
    description: 'Username for Dockerhub login'
  dockerhub_password:
    description: 'Password for Dockerhub login'

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - uses: docker/build-push-action@v6
      with:
        tags: ${{ inputs.name }}:${{ inputs.tag }}
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs. dockerfile }}
        push: ${{ inputs.push}}
        platforms: linux/amd64,linux/arm64
